try {
  const path = require('path');
  const restApi = require('cybersource-rest-client');
  const cyberSourceConfig = require(path.resolve('config/CyberSource.js'));

  const apiClient = new restApi.ApiClient();
  const instance = new restApi.PaymentsApi(cyberSourceConfig, apiClient);
  const requestData = restApi.CreatePaymentRequest.constructFromObject({
    tokenInformation: {
      transientTokenJwt: 'TBD generated by drop-in UI'
    },
    orderInformation: {
      billTo: {
        email: '',
        firstName: 'David',
        lastName: 'Balmer',
        address1: '100 Main Street',
        locality: 'Alameda', // city
        country: 'US', // two character ISO code
        administrativeArea: 'CA', // state code
        postalCode: '94501' // zipcode
      },
      amountDetails: {
        currency: 'USD',
        totalAmount: '0' // zero dollar auth
      }
    },
    processingInformation: {
      actionList: [
        'TOKEN_CREATE' // create the following token types
      ],
      actionTokenTypes: [ // create both of these at the same time using transient token
        'customer',
        'paymentInstrument'
      ],
      capture: false, // auth only
      commerceIndicator: 'internet' // Default value for authorizations and E-commerce orders placed from a website
    },
    clientReferenceInformation: {
      code: 'some-order-id'
    }
  });
  
  instance.createPayment(requestData, function (error, data, response) {
    if (response) {
      console.log('\n *** Response ***\n', JSON.stringify(response));
    }
    if (error) {
      console.log('\n *** Error ***\n', JSON.stringify(error));
    } else if (data) {
      console.log('\n *** Response Data returned ***\n', JSON.stringify(data));
    }    
  });
} catch (err) {
  console.error(err);
}
